MODEL:
  BACKBONE:
    FREEZE_AT: 0
    NAME: "build_resnet_backbone"
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  RESNETS:
    DEPTH: 50
    STEM_TYPE: "basic"  # not used
    STEM_OUT_CHANNELS: 64
    STRIDE_IN_1X1: False
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    # NORM: "SyncBN"
    RES5_MULTI_GRID: [1, 1, 1]  # not used
DATASETS:
  TRAIN: ("pascal-person-part_parsing_train",)
  TEST: ("pascal-person-part_parsing_test",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.0004
  STEPS: (14400, 15200)
  MAX_ITER: 16000  # 150 ep for ppp train with 1716 images
  WARMUP_FACTOR: 0.000001
  WARMUP_ITERS: 500
  WEIGHT_DECAY: 0.05
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 0.1
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
  AMP:
    ENABLED: True
INPUT:
  MIN_SIZE_TRAIN: (512, 640, 704, 768, 800, 864)
  MAX_SIZE_TRAIN: 1400
  DATASET_MAPPER_NAME: "m2fp_parsing"
TEST:
  EVAL_PERIOD: 1000
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 4
VERSION: 2
