_BASE_: maskformer2_R50b_bs64_60k.yaml
MODEL:
  WEIGHTS: "./weights/R-101a.pkl"
  # When using pre-trained models in Detectron1 or any MSRA(resnet a series) models,
  # std has been absorbed into its conv1 weights, so the std needs to be set 1.
  # Otherwise, use [57.375, 57.120, 58.395] (ImageNet std)
  PIXEL_MEAN: [ 103.530, 116.280, 123.675 ]
  PIXEL_STD: [ 1.0, 1.0, 1.0 ]
  RESNETS:
    DEPTH: 101
    STEM_TYPE: "basic"  # not used
    STEM_OUT_CHANNELS: 64
    STRIDE_IN_1X1: True
    OUT_FEATURES: [ "res2", "res3", "res4", "res5" ]
    # NORM: "SyncBN"
    RES5_MULTI_GRID: [ 1, 1, 1 ]  # not used
  MASK_FORMER:
    TEST:
      SEMANTIC_ON: True
      INSTANCE_ON: False
      PANOPTIC_ON: False
      OVERLAP_THRESHOLD: 0.8
      OBJECT_MASK_THRESHOLD: 0.8
INPUT:
  FORMAT: "BGR"  # for resnet a
TEST:
  AUG:
    ENABLED: True # use flip test
    FLIP: True
