_BASE_: maskformer2_R50_bs128_150ep.yaml
MODEL:
  WEIGHTS: "./weights/R-101.pkl"
  RESNETS:
    DEPTH: 101
    STEM_TYPE: "basic"  # not used
    STEM_OUT_CHANNELS: 64
    STRIDE_IN_1X1: False
    OUT_FEATURES: [ "res2", "res3", "res4", "res5" ]
    # NORM: "SyncBN"
    RES5_MULTI_GRID: [ 1, 1, 1 ]  # not used
  MASK_FORMER:
    TEST:
      SEMANTIC_ON: True
      INSTANCE_ON: False
      PANOPTIC_ON: False
      OVERLAP_THRESHOLD: 0.8
      OBJECT_MASK_THRESHOLD: 0.8
SOLVER:
  IMS_PER_BATCH: 64 # 16
  BASE_LR: 0.0004  # 0.0001
  MAX_ITER: 70000  # 280000
INPUT:
  DATASET_MAPPER_NAME: "mask_former_semantic"
  SINGLE_HUMAN:
    SIZES: ([384, 512],)
    SCALE_FACTOR: 0.3
    ROTATION: True
    ROT_FACTOR: 40
TEST:
  EVAL_PERIOD: 10000
  AUG:
    ENABLED: False
    MIN_SIZES: [ 384 ]
    MAX_SIZE: 3584
    FLIP: True
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 4
