_BASE_: ../Base-CIHP-Parsing.yaml
MODEL:
  META_ARCHITECTURE: "M2FP"
  SEM_SEG_HEAD:
    NAME: "M2FPHead"
    IGNORE_VALUE: 255
    NUM_CLASSES: 21
    LOSS_WEIGHT: 1.0
    CONVS_DIM: 256
    MASK_DIM: 256
    NORM: "GN"
    # pixel decoder
    PIXEL_DECODER_NAME: "MSDeformAttnPixelDecoder"
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    DEFORMABLE_TRANSFORMER_ENCODER_IN_FEATURES: ["res3", "res4", "res5"]
    COMMON_STRIDE: 4
    TRANSFORMER_ENC_LAYERS: 6
  M2FP:
    TRANSFORMER_DECODER_NAME: "MultiScaleMaskedTransformerDecoder"
    TRANSFORMER_IN_FEATURE: "multi_scale_pixel_decoder"
    DEEP_SUPERVISION: True
    NO_OBJECT_WEIGHT: 0.1
    CLASS_WEIGHT: 2.0
    MASK_WEIGHT: 5.0
    DICE_WEIGHT: 5.0
    HIDDEN_DIM: 256
    NUM_OBJECT_QUERIES: 100
    NHEADS: 8
    DROPOUT: 0.0
    DIM_FEEDFORWARD: 2048
    ENC_LAYERS: 0
    PRE_NORM: False
    ENFORCE_INPUT_PROJ: False
    SIZE_DIVISIBILITY: 32
    DEC_LAYERS: 10  # 9 decoder layers, add one for the loss on learnable query
    TRAIN_NUM_POINTS: 12544
    OVERSAMPLE_RATIO: 3.0
    IMPORTANCE_SAMPLE_RATIO: 0.75
    TEST:
      SEMANTIC_ON: False
      PARSING_ON: True
      OVERLAP_THRESHOLD: 0.8
      OBJECT_MASK_THRESHOLD: 0.8
      PARSING:
        METRICS: ("mIoU", "APr", "APp", "APh")
        PARSING_INS_SCORE_THR: 0.3
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.0008
  STEPS: (235000, 250000)
  MAX_ITER: 265000  # 150 ep for cihp train with 28280 images
INPUT:
  MIN_SIZE_TEST: 640
TEST:
  EVAL_PERIOD: 10000
  AUG:
    ENABLED: False
    MIN_SIZES: (640,)
    MAX_SIZE: 1400
    FLIP: True
